In [4]:
import csv


with open('1D_param.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    print('reader',reader)
    for row in reader:
        print(row)                              #you can remove this, see below
        file_name ='{0}.txt'.format(row['rotate_20x']) 
        with open(file_name, 'w') as f:
            f.write(row['Seq'])

reader <csv.DictReader object at 0x7faa647649a0>
{'': 'z/y-shear'}

KeyError: 'rotate_20x'

In [152]:
import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt

In [88]:
df_1Dparam = pd.read_csv ('1D_param.csv')

In [89]:
df_1Dparam.head(2)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,rotate_20x,0,0,0,0,20,0,0,0,0,0,0,0
1,rotate_5x,0,0,0,0,5,0,0,0,0,0,0,0

In [90]:
name  = df_1Dparam.iloc[1]

In [91]:
df_1Dparam.columns = ['fl_name','x_shift' ,'y_shift' ,'z_shift',
                      'z_angle' ,'x_angle' ,'y_angle',
                      'x_scale' ,'y_scale' ,'z_scale',
                      'yx_shear' ,'zx_shear','zy_shear']

In [174]:
df_1Dparam.head()

,fl_name,x_shift,y_shift,z_shift,z_angle,x_angle,y_angle,x_scale,y_scale,z_scale,yx_shear,zx_shear,zy_shear
0,rotate_20x,0,0,0,0,20,0,0,0,0,0,0,0
1,rotate_5x,0,0,0,0,5,0,0,0,0,0,0,0
2,rotate_10x,0,0,0,0,10,0,0,0,0,0,0,0

In [191]:
row = df_1Dparam.loc[0, :].values
row_str = np.array2string(row[1:], precision=2, separator=' ')
print(type(row))
print(row)
print(row_str[1:-1])

<class 'numpy.ndarray'>
['rotate_20x' 0 0 0 0 20 0 0 0 0 0 0 0]
0 0 0 0 20 0 0 0 0 0 0 0

In [146]:
param_name = str(row[1:])
print(param_name)

[0 0 0 0 20 0 0 0 0 0 0 0]

In [192]:
for index in range(len(df_1Dparam)):
     with open(str(row[0]) +  '.1D', 'w') as output:
        #output.write(str(row[1:]),sep='')
        print(str(row_str[1:-1]), sep=' ', file=output)

In [113]:
ele= str(row[1:])
print(ele)
print(type(ele))

[0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0]
<class 'str'>

In [117]:
with open(str(row[0]) +  '.1D', 'w') as output:
    output.write(" ".join(str(row[1:])))

In [125]:
content = df_1Dparam.loc[0, :].to_string()
print(content, file=open('my_file.txt', 'w'))

In [134]:
df_1Dparam.loc[0, :]

fl_name     rotate_20x
x_shift              0
y_shift              0
z_shift              0
z_angle              0
x_angle             20
y_angle              0
x_scale              0
y_scale              0
z_scale              0
yx_shear             0
zx_shear             0
zy_shear             0
Name: 0, dtype: object

In [164]:
a_str = np.array2string(row, precision=2, separator=' ')
print(a_str[2:-1])

rotate_20x' 0 0 0 0 20 0 0 0 0 0 0 0